#+title: some extensions to pass

Here are some extensions to [[https://www.passwordstore.org/][pass]].  They go in =~/.password-store/.extensions/=

* Install

#+begin_example
$ ./install.sh [force]
#+end_example

This will copy ~*.bash~ to the extensions directory if the file does not yet exist there.  If it exists and differs, a patch is emitted.  If "force" option, then the target is overwritten.

* Summary of extensions

** Mine

*** tail.bash

Output all but first (password) line.

#+begin_example
$ pass tail path/to/entry
#+end_example

*** data.bash 

Access non-password data in an entry.

This assumes the entry follows this basic form:
#+begin_example
<key> : <value>
#+end_example

With:

- ~<key>~ :: Must not start with a space but may have internal spaces.
- ~:~ :: May be surrounded by optional spaces.
- ~<value>~ :: May start on same line as ~<key> :~ or on the subsequent line and may be multiple lines.  Any ~<value>~ line on its own line MUST start with at least one white space character.
  

Usage:

#+begin_example
$ pass data [-k|--key key] ... [-s|--strip] path/to/entry
#+end_example

Multiple ~-k|--key key~ options are accepted and the query key may be
literal or a regular expression.


Note, output (without ~-s|--strip~) is essentially YAML.  One can form JSON
with, eg,

#+begin_example
$ pass data -k key path/to/entry | yq
#+end_example

However, while this script allows repeated keys, YAML does not.

** Others

- otp.bash :: from https://github.com/tadfisher/pass-otp (GPLv3)

- index.bash :: from https://github.com/sboesebeck/pass-index (Apache-2.0)

* Usage

These extensions are available for you to use under the terms of the GPLv3 license (see LICENSE file) or as otherwise indicated.



